### ISSUE TITLE
Update to version 2

### ISSUE THREAD

**Issue by georapbox** [georapbox/immutable-arrays#3]
### TODO
- [x] Update devDependencies, especially Webpack to v4 and Babel to v7
- [x] Provide CommonJS bundle alongside with the UMD bundle
- [x] Do not include distributable folders in source control
